# Generated by Django 5.2.11 on 2026-05-28 07:06

import django.db.models.deletion
import jdatetime
import product.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ورق')),
                ('thickness', models.DecimalField(decimal_places=1, help_text='مثال: 16.0', max_digits=4, verbose_name='ضخامت (میلی\u200cمتر)')),
            ],
            options={
                'verbose_name': 'متریال',
                'verbose_name_plural': 'متریال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='رنگ')),
                ('parts_list_key', models.CharField(blank=True, max_length=255, verbose_name='مسیر فایل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('default_size', models.CharField(blank=True, max_length=100, verbose_name='سایز پیش\u200cفرض')),
                ('default_colors', models.JSONField(blank=True, default=dict, verbose_name='رنگ\u200cهای پیش\u200cفرض')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='نماینده')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='شماره سفارش')),
                ('created_at', product.fields.PersianDateField(default=jdatetime.date.today, verbose_name='تاریخ سفارش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('planned', 'برنامه\u200cریزی شده'), ('producing', 'در حال تولید'), ('completed', 'تکمیل شده')], default='draft', max_length=20, verbose_name='وضعیت سفارش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.customer', verbose_name='مشتری')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نماینده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='اندازه')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لیست سفارش',
                'verbose_name_plural': 'لیست سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], max_length=20, verbose_name='قطعه')),
                ('code', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('جناغی', 'جناغی'), ('بتنی', 'بتنی')], max_length=20, verbose_name='کد رنگ')),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercolor', to='product.orderitem', verbose_name='آیتم سفارش')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PackagingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField(verbose_name='شماره واحد')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/packaging/', verbose_name='QR بسته\u200cبندی')),
                ('is_packed', models.BooleanField(default=False, verbose_name='بسته\u200cبندی شده')),
                ('packed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته\u200cبندی')),
                ('is_shipped', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_units', to='product.orderitem')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_units', to=settings.AUTH_USER_MODEL, verbose_name='بسته\u200cبندی\u200cکننده')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_units', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
            ],
            options={
                'verbose_name': 'واحد بسته\u200cبندی',
                'verbose_name_plural': 'واحدهای بسته\u200cبندی و ارسال',
                'unique_together': {('order_item', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قطعه')),
                ('length', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='طول (X)')),
                ('width', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='عرض (Y)')),
                ('grain', models.CharField(blank=True, max_length=100, verbose_name='دسته')),
                ('pname', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('turn', models.BooleanField(blank=True, default=False, verbose_name='turn')),
                ('f26', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F26')),
                ('f18', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F18')),
                ('f4', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F4')),
                ('f5', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F5')),
                ('f3', models.CharField(blank=True, max_length=100, verbose_name='بارکد F3')),
                ('f2', models.CharField(blank=True, max_length=100, verbose_name='نام قطعه F2')),
                ('routing_code', models.CharField(max_length=255, verbose_name='تحویل به مرحله')),
                ('base_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='product.part', verbose_name='قطعه پایه')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='product.material', verbose_name='نوع ورق')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
            },
        ),
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد در هر محصول')),
                ('color_part', models.CharField(blank=True, choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], max_length=20, null=True, verbose_name='بخش رنگی')),
                ('allow_material_override', models.BooleanField(default=False, verbose_name='امکان تغییر متریال با رنگ')),
                ('color_material_map', models.JSONField(blank=True, default=dict, verbose_name='نگاشت رنگ به متریال')),
                ('size_affected', models.BooleanField(default=False, verbose_name='تحت تأثیر اندازه')),
                ('size_adjustment_rule', models.CharField(blank=True, help_text='مثال: length+length_diff, width/3', max_length=100, verbose_name='قانون تغییر اندازه')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.part')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='product.product')),
            ],
            options={
                'verbose_name': 'فرمول ساخت',
                'verbose_name_plural': 'فرمول\u200cهای ساخت',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productcategory', verbose_name='دسته'),
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='مرحله')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('created_at', product.fields.PersianDateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='product.orderitem', verbose_name='آیتم سفارش')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش تولید',
                'verbose_name_plural': 'گزارش\u200cهای تولید',
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='ایستگاه کاری')),
                ('step_order', models.PositiveIntegerField(verbose_name='اولویت مرحله')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد قطعه')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار مرحله قبل'), ('pending', 'آماده انجام'), ('done', 'تکمیل شده')], default='waiting', max_length=20, verbose_name='وضعیت تسک')),
                ('completed_at', product.fields.PersianDateField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='product.order', verbose_name='سفارش')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.part', verbose_name='قطعه')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
            ],
            options={
                'verbose_name': 'وظیفه تولید',
                'verbose_name_plural': 'وظایف تولید',
                'ordering': ['order', 'part', 'step_order'],
            },
        ),

        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='مرحله کاری')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کارگر',
                'verbose_name_plural': 'پروفایل کارگران',
            },
        ),
    ]
