# Generated by Django 5.2.11 on 2026-05-28 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, verbose_name='پلاک / شناسه محموله')),
                ('shipped_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('packaging_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_logs', to='product.packagingunit', verbose_name='واحد بسته\u200cبندی')),
                ('shipped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
            ],
            options={
                'verbose_name': 'لاگ محموله',
                'verbose_name_plural': 'لاگ\u200cهای محموله',
            },
        ),
    ]
