# Generated by Django 6.0.6 on 2026-07-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_shipmentlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentlog',
            options={'verbose_name': 'بارگیری', 'verbose_name_plural': 'بارگیری'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_increment_per_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد افزایش قیمت به ازای هر سانتی\u200cمتر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='shipmentlog',
            name='packaging_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_logs', to='product.packagingunit', verbose_name='بسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='shipmentlog',
            name='plate_number',
            field=models.CharField(max_length=50, verbose_name='پلاک'),
        ),
    ]
