# Generated by Django 5.2.11 on 2026-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_paintingprocess_order_due_date_order_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='تاریخ دقیق تعطیلی (میلادی)', unique=True, verbose_name='تاریخ میلادی')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='مناسبت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
            },
        ),
    ]
