# Generated by Django 5.2.11 on 2026-07-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_paintingprocess_order_due_date_order_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_tasks', to='product.orderitem', verbose_name='آیتم سفارش مرتبط (برای نقاشی)'),
        ),
    ]
