# Generated by Django 5.2.11 on 2026-07-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productiontask_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='color_part',
            field=models.CharField(blank=True, max_length=50, verbose_name='بخش رنگی (بدنه، درب، ...)'),
        ),
    ]
