# Generated by Django 5.2.11 on 2026-08-03 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_codes', models.JSONField(blank=True, help_text='لیست کدهای رنگی که این قانون برای آن\u200cها اعمال می\u200cشود (خالی = همه رنگ\u200cها)', null=True, verbose_name='کدهای رنگ')),
                ('priority', models.IntegerField(default=100, help_text='عدد بالاتر = اولویت بیشتر در زمان\u200cبندی', verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('painting_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.paintingstage', verbose_name='مرحله نقاشی (اختیاری)')),
                ('process', models.ForeignKey(blank=True, help_text='محدود کردن مرحله به یک روند خاص', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.paintingprocess', verbose_name='روند نقاشی (اختیاری)')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='product.workerprofile', verbose_name='کارگر')),
            ],
            options={
                'verbose_name': 'قانون تخصیص کارگر',
                'verbose_name_plural': 'قوانین تخصیص کارگر',
                'ordering': ['-priority', 'worker'],
            },
        ),
    ]
