# Generated by Django 5.2.11 on 2026-08-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_paintingassignmentrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingassignmentrule',
            name='rule_type',
            field=models.CharField(choices=[('priority', 'فقط اولویت\u200cدهی'), ('exclusive', 'محدودکننده'), ('exclusion', 'منع\u200cکننده')], default='priority', help_text='فقط اولویت\u200cدهی، محدودکننده (کارگر فقط همین تسک\u200cها را بگیرد) یا منع\u200cکننده', max_length=20, verbose_name='نوع قانون'),
        ),
        migrations.AlterField(
            model_name='paintingassignmentrule',
            name='priority',
            field=models.IntegerField(default=100, help_text='عدد بالاتر = اولویت بیشتر در زمان\u200cبندی (فقط برای نوع اولویت\u200cدهی)', verbose_name='اولویت'),
        ),
    ]
