# Generated by Django 5.2.11 on 2026-08-18

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_paintingassignmentrule_rule_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='break_end',
            field=models.TimeField(default=datetime.time(13, 30), verbose_name='پایان استراحت'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='break_start',
            field=models.TimeField(default=datetime.time(12, 30), verbose_name='شروع استراحت'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_end',
            field=models.TimeField(default=datetime.time(16, 30), verbose_name='پایان کار'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='شروع کار'),
        ),
    ]
