# Generated by Django 5.2.11 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_workerprofile_work_hours'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['station_name', 'scheduled_start'], name='prod_task_station_start_idx'),
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['assigned_worker', 'scheduled_start'], name='prod_task_worker_start_idx'),
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['order_item', 'station_name', 'status'], name='prod_task_item_station_status_idx'),
        ),
    ]
