# Generated by Django 5.2.11 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productiontask_indexes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='skill_costs',
            new_name='skill_priority',
        ),
    ]
