# Generated by Django 5.2.11 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_skill_costs_workerprofile_skill_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='skill_priority',
            field=models.JSONField(default=dict, verbose_name='اولویت/میزان مهارت کارگر'),
        ),
    ]
