# Generated by Django 5.2.11 on 2026-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_workerprofile_skill_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد انجام\u200cشده'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='is_manual_item_task',
            field=models.BooleanField(default=False, verbose_name='تسک عملیات مشترک روی آیتم (بدون بارکد دستگاه)'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='manual_reference_file',
            field=models.CharField(blank=True, max_length=255, verbose_name='فایل مرجع (برای تسک\u200cهای عملیات مشترک)'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skill_priority',
            field=models.JSONField(blank=True, default=dict, verbose_name='اولویت/میزان مهارت کارگر'),
        ),
    ]
