# Generated by Django 5.2.11 on 2026-09-06 08:56

from django.db import migrations


def backfill_completed_quantity(apps, schema_editor):
    ProductionTask = apps.get_model('product', 'ProductionTask')
    done_tasks = ProductionTask.objects.filter(status='done')
    count = 0
    for task in done_tasks:
        if task.completed_quantity != task.quantity:
            task.completed_quantity = task.quantity
            task.save(update_fields=['completed_quantity'])
            count += 1
    print(f"Backfilled completed_quantity for {count} done tasks.")


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_prod_task_station_start_idx_product_pro_station_483d1d_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_completed_quantity, reverse_code=migrations.RunPython.noop),
    ]
