# Generated by Django 5.2.11 on 2026-09-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_backfill_completed_quantity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productiontask',
            new_name='product_pro_station_483d1d_idx',
            old_name='prod_task_station_start_idx',
        ),
        migrations.RenameIndex(
            model_name='productiontask',
            new_name='product_pro_assigne_824415_idx',
            old_name='prod_task_worker_start_idx',
        ),
        migrations.RenameIndex(
            model_name='productiontask',
            new_name='product_pro_order_i_cb6f35_idx',
            old_name='prod_task_item_station_status_idx',
        ),
        migrations.RemoveField(
            model_name='productiontask',
            name='is_manual_item_task',
        ),
        migrations.RemoveField(
            model_name='productiontask',
            name='manual_reference_file',
        ),
    ]
