# Generated by Django 5.2.11 on 2026-09-07 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_manual_task_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='ایستگاه')),
                ('event_type', models.CharField(choices=[('started', 'شروع'), ('done', 'اتمام'), ('reassigned', 'تغییر کارگر'), ('status_changed', 'تغییر وضعیت دستی')], max_length=20, verbose_name='نوع رویداد')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد در این رویداد')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('new_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارگر جدید')),
                ('old_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارگر قبلی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_events', to='product.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to='product.orderitem', verbose_name='آیتم سفارش')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='product.productiontask', verbose_name='تسک تولید')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'رویداد تولید',
                'verbose_name_plural': 'رویدادهای تولید',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_item', 'station_name'], name='product_pro_order_i_77e230_idx'), models.Index(fields=['task', 'created_at'], name='product_pro_task_id_9f4fbd_idx'), models.Index(fields=['event_type', 'created_at'], name='product_pro_event_t_828514_idx')],
            },
        ),
    ]
