# Generated by Django 5.2.11 on 2026-09-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0015_productionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='consumption_per_unit',
            field=models.DecimalField(decimal_places=3, default=1, help_text='مقدار مصرف به ازای هر قطعه', max_digits=10, verbose_name='مقدار مصرف به ازای هر قطعه'),
        ),
        migrations.AddField(
            model_name='material',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_materials', to='inventory.rawmaterial', verbose_name='ماده اولیه انبار (برای مصرف خودکار)'),
        ),
    ]
