# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام روند')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد روند')),
                ('color_codes', models.JSONField(default=list, verbose_name='لیست کدهای رنگی مرتبط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان تخمینی (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'روند نقاشی',
                'verbose_name_plural': 'روندهای نقاشی',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaintingProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='ترتیب')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='زمان انجام (دقیقه)')),
                ('drying_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان خشک\u200cشدن (دقیقه)')),
                ('required_skill', models.CharField(choices=[('painter', 'نقاش'), ('general', 'زیرکار'), ('helper', 'کمک')], default='painter', max_length=50, verbose_name='مهارت مورد نیاز')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='حداقل دما (سانتی\u200cگراد)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='حداکثر دما (سانتی\u200cگراد)')),
                ('humidity_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='حداکثر رطوبت (%)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='اجباری')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='painting.paintingprocess', verbose_name='روند')),
            ],
            options={
                'verbose_name': 'مرحله نقاشی',
                'verbose_name_plural': 'مراحل نقاشی',
                'ordering': ['process', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PaintingAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_codes', models.JSONField(blank=True, null=True, verbose_name='کدهای رنگ')),
                ('rule_type', models.CharField(choices=[('priority', 'اولویت\u200cدهی'), ('exclusive', 'محدودکننده'), ('exclusion', 'منع\u200cکننده')], default='priority', max_length=20, verbose_name='نوع قانون')),
                ('priority', models.IntegerField(default=100, verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_assignment_rules', to='accounts.worker', verbose_name='کارگر')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='painting.paintingprocess', verbose_name='روند نقاشی')),
                ('painting_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='painting.paintingprocessstage', verbose_name='مرحله نقاشی')),
            ],
            options={
                'verbose_name': 'قانون تخصیص نقاشی',
                'verbose_name_plural': 'قوانین تخصیص نقاشی',
                'ordering': ['-priority', 'worker'],
            },
        ),
        migrations.CreateModel(
            name='PaintingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'برنامه نقاشی',
                'verbose_name_plural': 'برنامه\u200cهای نقاشی',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaintingScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField(verbose_name='شروع برنامه\u200cریزی شده')),
                ('scheduled_end', models.DateTimeField(verbose_name='پایان برنامه\u200cریزی شده')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع واقعی')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان واقعی')),
                ('status', models.CharField(default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('is_cascade_moved', models.BooleanField(default=False, verbose_name='جابه\u200cجایی زنجیره\u200cای')),
                ('painting_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painting.paintingprocessstage', verbose_name='مرحله نقاشی')),
            ],
            options={
                'verbose_name': 'آیتم برنامه نقاشی',
                'verbose_name_plural': 'آیتم\u200cهای برنامه نقاشی',
                'ordering': ['schedule', 'scheduled_start'],
            },
        ),
    ]
