# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('painting', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingscheduleitem',
            name='production_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionoperation', verbose_name='عملیات تولید'),
        ),
        migrations.AddField(
            model_name='paintingscheduleitem',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='painting.paintingschedule', verbose_name='برنامه'),
        ),
        migrations.AddField(
            model_name='paintingscheduleitem',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.worker', verbose_name='کارگر'),
        ),
        migrations.AlterUniqueTogether(
            name='paintingprocessstage',
            unique_together={('process', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='paintingschedule',
            unique_together={('date',)},
        ),
    ]
