# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_uom_itemcategory_item_stocklocation_stocklot_and_more'),
        ('production', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=50, unique=True, verbose_name='شماره صدور')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان صدور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customerorder', verbose_name='سفارش مرتبط')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to=settings.AUTH_USER_MODEL, verbose_name='صادرکننده')),
            ],
            options={
                'verbose_name': 'صدور مواد',
                'verbose_name_plural': 'صدورهای مواد',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot', verbose_name='لات')),
                ('material_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.materialissue', verbose_name='صدور مواد')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_items_from', to='inventory.stocklocation', verbose_name='مکان مبدأ')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_items_to', to='inventory.stocklocation', verbose_name='مکان مقصد')),
            ],
            options={
                'verbose_name': 'آیتم صدور مواد',
                'verbose_name_plural': 'آیتم\u200cهای صدور مواد',
                'ordering': ['material_issue', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار مصرف')),
                ('consumption_date', models.DateTimeField(verbose_name='تاریخ مصرف')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('consumed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مصرف\u200cکننده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
                ('production_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionoperation', verbose_name='عملیات تولید')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorder', verbose_name='سفارش تولید')),
                ('material_issue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='warehouse.materialissueitem', verbose_name='آیتم صدور')),
            ],
            options={
                'verbose_name': 'مصرف مواد',
                'verbose_name_plural': 'مصرف مواد',
                'ordering': ['-consumption_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='شماره درخواست')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت شده'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('processed', 'پردازش شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('needed_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نیاز')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='فوری')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_material_requests', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customerorder', verbose_name='سفارش مرتبط')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست مواد',
                'verbose_name_plural': 'درخواست\u200cهای مواد',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار درخواستی')),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='مقدار تایید شده')),
                ('issued_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار صادر شده')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.materialrequest', verbose_name='درخواست مواد')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items_from', to='inventory.stocklocation', verbose_name='مکان مبدأ')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items_to', to='inventory.stocklocation', verbose_name='مکان مقصد')),
            ],
            options={
                'verbose_name': 'آیتم درخواست مواد',
                'verbose_name_plural': 'آیتم\u200cهای درخواست مواد',
                'ordering': ['material_request', 'id'],
            },
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='material_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.materialrequestitem', verbose_name='آیتم درخواست مرتبط'),
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار مورد نیاز')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار رزرو شده')),
                ('issued_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار صادر شده')),
                ('consumed_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار مصرف شده')),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار مرجوع شده')),
                ('wasted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار ضایعات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('planned', 'برنامه\u200cریزی شده'), ('requested', 'درخواست شده'), ('issued', 'صادر شده'), ('consumed', 'مصرف شده'), ('returned', 'مرجوع شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('needed_by_date', models.DateField(blank=True, null=True, verbose_name='نیاز به تاریخ')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('customer_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='sales.customerorderitem', verbose_name='آیتم سفارش')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requirements', to='inventory.item', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'نیاز مواد اولیه',
                'verbose_name_plural': 'نیازهای مواد اولیه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='material_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.materialrequirement', verbose_name='نیاز مرتبط'),
        ),
        migrations.CreateModel(
            name='MaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='شماره مرجوعی')),
                ('returned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان مرجوعی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('returned', 'مرجوع شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customerorder', verbose_name='سفارش مرتبط')),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_returns', to=settings.AUTH_USER_MODEL, verbose_name='مرجوع\u200cکننده')),
            ],
            options={
                'verbose_name': 'مرجوعی مواد',
                'verbose_name_plural': 'مرجوعی\u200cهای مواد',
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل مرجوعی')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot', verbose_name='لات')),
                ('material_issue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.materialissueitem', verbose_name='آیتم صدور مرتبط')),
                ('material_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.materialreturn', verbose_name='مرجوعی')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items_from', to='inventory.stocklocation', verbose_name='مکان مبدأ')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items_to', to='inventory.stocklocation', verbose_name='مکان مقصد')),
            ],
            options={
                'verbose_name': 'آیتم مرجوعی',
                'verbose_name_plural': 'آیتم\u200cهای مرجوعی',
                'ordering': ['material_return', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار ضایعات')),
                ('waste_date', models.DateTimeField(verbose_name='تاریخ ضایعات')),
                ('reason', models.CharField(max_length=255, verbose_name='دلیل ضایعات')),
                ('disposal_method', models.CharField(blank=True, max_length=100, verbose_name='روش دفع')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هزینه ضایعات')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastes', to='inventory.item', verbose_name='کالا')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation', verbose_name='مکان')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'ضایعات مواد',
                'verbose_name_plural': 'ضایعات مواد',
                'ordering': ['-waste_date'],
            },
        ),
    ]
