# Generated by Django 5.2.11 on 2026-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialconsumption',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='کلید idempotency'),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='کلید idempotency'),
        ),
    ]
