# Generated by Django 5.2.11 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_materialconsumption_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconsumption',
            name='material_issue_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='consumptions', to='warehouse.MaterialIssueItem', verbose_name='آیتم صدور'),
        ),
    ]
