# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bom', '0001_initial'),
        ('inventory', '0002_uom_itemcategory_item_stocklocation_stocklot_and_more'),
        ('planning', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=100, verbose_name='نام عملیات')),
                ('operation_code', models.CharField(max_length=50, verbose_name='کد عملیات')),
                ('sequence', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار'), ('ready', 'آماده'), ('in_progress', 'در حال انجام'), ('paused', 'متوقف موقت'), ('completed', 'تکمیل شده'), ('skipped', 'رد شده'), ('failed', 'ناموفق')], default='waiting', max_length=20, verbose_name='وضعیت')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع برنامه\u200cریزی شده')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان برنامه\u200cریزی شده')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع واقعی')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان واقعی')),
                ('setup_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان آماده\u200cسازی (دقیقه)')),
                ('run_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان اجرا (دقیقه)')),
                ('completed_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد تکمیل شده')),
                ('scrapped_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد دورریز')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.workcenter', verbose_name='مرکز کار')),
            ],
            options={
                'verbose_name': 'عملیات تولید',
                'verbose_name_plural': 'عملیات\u200cهای تولید',
                'ordering': ['production_order', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='OperationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='زمان شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('quantity_produced', models.PositiveIntegerField(default=0, verbose_name='تعداد تولید شده')),
                ('quantity_scrapped', models.PositiveIntegerField(default=0, verbose_name='تعداد دورریز')),
                ('setup_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان آماده\u200cسازی')),
                ('run_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان اجرا')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.worker', verbose_name='کارگر')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='production.productionoperation', verbose_name='عملیات')),
            ],
            options={
                'verbose_name': 'اجرای عملیات',
                'verbose_name_plural': 'اجراهای عملیات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='شماره سفارش تولید')),
                ('bom_revision', models.CharField(max_length=20, verbose_name='Revision BOM')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('planned', 'برنامه\u200cریزی شده'), ('released', 'آغاز شده'), ('in_progress', 'در حال انجام'), ('paused', 'متوقف موقت'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='شروع برنامه\u200cریزی شده')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='پایان برنامه\u200cریزی شده')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع واقعی')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان واقعی')),
                ('priority', models.PositiveSmallIntegerField(default=3, verbose_name='اولویت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='sales.customerorder', verbose_name='سفارش مشتری')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='planning.routing', verbose_name='مسیر تولید')),
            ],
            options={
                'verbose_name': 'سفارش تولید',
                'verbose_name_plural': 'سفارش\u200cهای تولید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.productionorder', verbose_name='سفارش تولید'),
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='شماره بچ')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('started', 'شروع شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='planned', max_length=20, verbose_name='وضعیت')),
                ('planned_quantity', models.PositiveIntegerField(verbose_name='تعداد برنامه\u200cریزی شده')),
                ('actual_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد واقعی')),
                ('scrapped_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد دورریز')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع برنامه\u200cریزی شده')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان برنامه\u200cریزی شده')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع واقعی')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان واقعی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.productionorder', verbose_name='سفارش تولید')),
            ],
            options={
                'verbose_name': 'بچ تولید',
                'verbose_name_plural': 'بچ\u200cهای تولید',
                'ordering': ['production_order', 'batch_number'],
                'unique_together': {('production_order', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('completed_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد تکمیل شده')),
                ('scrapped_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد دورریز')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bom.bom', verbose_name='BOM')),
                ('customer_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_items', to='sales.customerorderitem', verbose_name='آیتم سفارش مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='محصول')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionorder', verbose_name='سفارش تولید')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.routing', verbose_name='مسیر تولید')),
            ],
            options={
                'verbose_name': 'آیتم سفارش تولید',
                'verbose_name_plural': 'آیتم\u200cهای سفارش تولید',
                'ordering': ['production_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='production_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.productionorderitem', verbose_name='آیتم سفارش تولید'),
        ),
        migrations.CreateModel(
            name='ProductionBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('serial_numbers', models.JSONField(blank=True, default=list, verbose_name='شماره سریال\u200cها')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionbatch', verbose_name='بچ')),
                ('production_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='production.productionorderitem', verbose_name='آیتم سفارش تولید')),
            ],
            options={
                'verbose_name': 'آیتم بچ تولید',
                'verbose_name_plural': 'آیتم\u200cهای بچ تولید',
                'ordering': ['batch', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WIPUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='شماره سریال')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('waiting', 'در انتظار'), ('completed', 'تکمیل شده'), ('scrapped', 'ضایعات')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_wip_units', to='production.productionoperation', verbose_name='عملیات فعلی')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_units', to='production.productionorder', verbose_name='سفارش تولید')),
                ('production_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_units', to='production.productionorderitem', verbose_name='آیتم سفارش تولید')),
            ],
            options={
                'verbose_name': 'واحد WIP',
                'verbose_name_plural': 'واحدهای WIP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WIPTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتقال')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_transfers_from', to='inventory.stocklocation', verbose_name='از مکان')),
                ('from_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='production.productionoperation', verbose_name='از عملیات')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_transfers_to', to='inventory.stocklocation', verbose_name='به مکان')),
                ('to_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='production.productionoperation', verbose_name='به عملیات')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انتقال\u200cدهنده')),
                ('wip_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='production.wipunit', verbose_name='واحد WIP')),
            ],
            options={
                'verbose_name': 'انتقال WIP',
                'verbose_name_plural': 'انتقال\u200cهای WIP',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'تخصیص داده شده'), ('accepted', 'پذیرفته شده'), ('started', 'شروع شده'), ('completed', 'تکمیل شده'), ('released', ' آزاد شده')], default='assigned', max_length=20, verbose_name='وضعیت')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تخصیص')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.worker', verbose_name='کارگر')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='production.productionoperation', verbose_name='عملیات')),
            ],
            options={
                'verbose_name': 'تخصیص عملیات',
                'verbose_name_plural': 'تخصیص\u200cهای عملیات',
                'ordering': ['-assigned_at'],
                'unique_together': {('operation', 'worker')},
            },
        ),
        migrations.AddIndex(
            model_name='productionoperation',
            index=models.Index(fields=['production_order', 'sequence'], name='production__product_6b8ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='productionoperation',
            index=models.Index(fields=['status', 'planned_start'], name='production__status_58dd32_idx'),
        ),
    ]
