# Generated by Django 5.2.11 on 2026-09-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationexecution',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.worker', verbose_name='کارگر'),
        ),
    ]
