# Generated by Django 5.2.11 on 2026-09-08 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_initial'),
        ('production', '0002_operationexecution_worker_nullable'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoperation',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operations', to=settings.AUTH_USER_MODEL, verbose_name='کارگر اختصاص یافته'),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='color_part',
            field=models.CharField(blank=True, max_length=20, verbose_name='بخش رنگی'),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='تکمیل شده در (جلالی)'),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='sales.customerorderitem', verbose_name='آیتم سفارش'),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='painting_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='painting.paintingprocessstage', verbose_name='مرحله نقاشی'),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='products.productpart', verbose_name='قطعه'),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_operations', to=settings.AUTH_USER_MODEL, verbose_name='اسکن شده توسط'),
        ),
    ]
