# Generated by Django 5.2.11 on 2026-09-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionoperation_assigned_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderitem',
            name='bom_revision',
            field=models.CharField(default='', max_length=20, verbose_name='Revision BOM'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='bom_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot BOM'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='routing_revision',
            field=models.CharField(default='', max_length=20, verbose_name='Revision Routing'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='routing_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot Routing'),
        ),
    ]
