# Generated by Django 5.2.11 on 2026-09-07 14:40

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='مناسبت')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='تکرار سالانه')),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='کد کارمندی')),
                ('station', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال'), ('quality', 'کنترل کیفیت')], max_length=50, verbose_name='ایستگاه کاری')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='مهارت\u200cها')),
                ('skill_priority', models.JSONField(blank=True, default=dict, verbose_name='اولویت مهارت\u200cها')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('work_start', models.TimeField(default=accounts.models._default_work_start, verbose_name='شروع کار')),
                ('work_end', models.TimeField(default=accounts.models._default_work_end, verbose_name='پایان کار')),
                ('break_start', models.TimeField(default=accounts.models._default_break_start, verbose_name='شروع استراحت')),
                ('break_end', models.TimeField(default=accounts.models._default_break_end, verbose_name='پایان استراحت')),
                ('hourly_rate', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='حقوق ساعتی')),
                ('excluded_items', models.ManyToManyField(blank=True, to='sales.customerorderitem', verbose_name='آیتم\u200cهای ممنوعه')),
                ('excluded_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='محصولات ممنوعه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارگر',
                'verbose_name_plural': 'کارگران',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('is_working', models.BooleanField(default=True, verbose_name='روز کاری')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ساعت اضافه کار')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.worker', verbose_name='کارگر')),
            ],
            options={
                'verbose_name': 'برنامه کاری کارگر',
                'verbose_name_plural': 'برنامه\u200cهای کاری کارگران',
                'ordering': ['date', 'worker'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
