# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='سطح')),
                ('is_certified', models.BooleanField(default=False, verbose_name='نیاز به گواهینامه')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قطعه تولید')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='کد')),
                ('length', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='طول')),
                ('width', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='عرض')),
                ('thickness', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='ضخامت')),
                ('grain', models.CharField(blank=True, max_length=20, verbose_name='جهت رگه')),
                ('f26', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F26')),
                ('f18', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F18')),
                ('f4', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F4')),
                ('f5', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F5')),
                ('f3', models.CharField(blank=True, max_length=100, verbose_name='بارکد F3')),
                ('f2', models.CharField(blank=True, max_length=100, verbose_name='نام فنی F2')),
                ('pname', models.CharField(blank=True, max_length=100, verbose_name='نام محصول')),
                ('turn', models.BooleanField(default=False, verbose_name='چرخش')),
                ('routing_code', models.CharField(blank=True, max_length=255, verbose_name='کد مسیر')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_parts', to='products.productpart', verbose_name='قطعه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_parts', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قطعه تولید',
                'verbose_name_plural': 'قطعات تولید',
                'ordering': ['product', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(default='A', max_length=20, verbose_name='Revision')),
                ('name', models.CharField(max_length=100, verbose_name='نام مسیر')),
                ('effective_date', models.DateField(verbose_name='تاریخ اجرا')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('obsolete', 'منسوخ شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('total_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان کل (دقیقه)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routings', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مسیر تولید',
                'verbose_name_plural': 'مسیرهای تولید',
                'ordering': ['product', '-effective_date'],
                'unique_together': {('product', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('capacity_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ظرفیت در ساعت')),
                ('efficiency_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='ضریب بازده')),
                ('setup_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان آماده\u200cسازی (دقیقه)')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه هر ساعت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'مرکز کار',
                'verbose_name_plural': 'مراکز کار',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('operation_name', models.CharField(max_length=100, verbose_name='نام عملیات')),
                ('operation_code', models.CharField(max_length=50, verbose_name='کد عملیات')),
                ('setup_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان آماده\u200cسازی (دقیقه)')),
                ('run_time_per_unit_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='زمان اجرا در واحد (دقیقه)')),
                ('queue_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان انتظار (دقیقه)')),
                ('is_inspection', models.BooleanField(default=False, verbose_name='بازرسی است')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='اجباری')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='planning.routing', verbose_name='مسیر تولید')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.workcenter', verbose_name='مرکز کار')),
            ],
            options={
                'verbose_name': 'عملیات مسیر تولید',
                'verbose_name_plural': 'عملیات\u200cهای مسیر تولید',
                'ordering': ['routing', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='RoutingDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', 'پایان تا شروع (Finish to Start)'), ('SS', 'شروع تا شروع (Start to Start)'), ('FF', 'پایان تا پایان (Finish to Finish)'), ('SF', 'شروع تا پایان (Start to Finish)')], default='FS', max_length=5, verbose_name='نوع وابستگی')),
                ('lag_minutes', models.PositiveIntegerField(default=0, verbose_name='تأخیر (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='planning.routing', verbose_name='مسیر تولید')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='planning.routingoperation', verbose_name='عملیات قبل')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='planning.routingoperation', verbose_name='عملیات بعد')),
            ],
            options={
                'verbose_name': 'وابستگی مسیر تولید',
                'verbose_name_plural': 'وابستگی\u200cهای مسیر تولید',
                'unique_together': {('routing', 'predecessor', 'successor')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('resource_type', models.CharField(choices=[('machine', 'ماشین'), ('tool', 'ابزار'), ('fixture', 'گیج و مهار'), ('measurement', 'دستگاه اندازه\u200cگیری')], default='machine', max_length=20, verbose_name='نوع')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='شماره سریال')),
                ('capacity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='ظرفیت')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='آخرین تعمیر')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='تعمیر بعدی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='planning.workcenter', verbose_name='مرکز کار')),
            ],
            options={
                'verbose_name': 'منبع',
                'verbose_name_plural': 'منابع',
                'ordering': ['work_center', 'code'],
                'unique_together': {('work_center', 'code')},
            },
        ),
    ]
