# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='کد')),
                ('barcode_type', models.CharField(choices=[('qr', 'QR Code'), ('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13'), ('upc', 'UPC')], default='qr', max_length=20, verbose_name='نوع بارکد')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه شی')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای بارکد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اسکن')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='تعداد اسکن')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
            ],
            options={
                'verbose_name': 'بارکد',
                'verbose_name_plural': 'بارکدها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50, verbose_name='فاز')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('partial', 'جزئی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='رکوردهای پردازش شده')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='رکوردهای ناموفق')),
                ('records_skipped', models.PositiveIntegerField(default=0, verbose_name='رکوردهای رد شده')),
                ('log', models.TextField(blank=True, verbose_name='لاگ')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='خطاها')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='هشدارها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'اجرای مهاجرت',
                'verbose_name_plural': 'اجرای\u200cهای مهاجرت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'به\u200cروزرسانی'), ('delete', 'حذف'), ('view', 'مشاهده'), ('export', 'خروجی'), ('import', 'ورودی'), ('login', 'ورود'), ('logout', 'خروج'), ('approve', 'تایید'), ('reject', 'رد'), ('cancel', 'لغو'), ('assign', 'تخصیص')], max_length=20, verbose_name='عملیات')),
                ('model_name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='شناسه شی')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='نماینده شی')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='تغییرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ تغییرات',
                'verbose_name_plural': 'لاگ\u200cهای تغییرات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action', 'timestamp'], name='reporting_a_user_id_f993a7_idx'), models.Index(fields=['model_name', 'object_id'], name='reporting_a_model_n_1c3af5_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sales', 'فروش'), ('production', 'تولید'), ('inventory', 'انبار'), ('warehouse', 'انبار مواد'), ('shipping', 'ارسال'), ('quality', 'کیفیت'), ('painting', 'نقاشی'), ('packaging', 'بسته\u200cبندی'), ('system', 'سیستم')], max_length=20, verbose_name='دسته رویداد')),
                ('event_type', models.CharField(choices=[('created', 'ایجاد'), ('updated', 'به\u200cروزرسانی'), ('deleted', 'حذف'), ('status_changed', 'تغییر وضعیت'), ('assigned', 'تخصیص'), ('started', 'شروع'), ('completed', 'تکمیل'), ('cancelled', 'لغو'), ('issued', 'صدور'), ('received', 'دریافت'), ('transferred', 'انتقال'), ('consumed', 'مصرف'), ('returned', 'مرجوعی'), ('inspected', 'بازرسی'), ('shipped', 'ارسال'), ('delivered', 'تحویل'), ('scrapped', 'ضایعات'), ('reserved', 'رزرو'), ('released', 'آزادسازی')], max_length=20, verbose_name='نوع رویداد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('occurred_at', models.DateTimeField(verbose_name='زمان رخ دادن')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه شی')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('is_system', models.BooleanField(default=False, verbose_name='رویداد سیستمی')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'رویداد کسب\u200cوکار',
                'verbose_name_plural': 'رویدادهای کسب\u200cوکار',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['category', 'event_type', 'occurred_at'], name='reporting_b_categor_d7992c_idx'), models.Index(fields=['content_type', 'object_id'], name='reporting_b_content_f250bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='MigrationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_type', models.CharField(choices=[('customer', 'مشتری'), ('order', 'سفارش'), ('order_item', 'آیتم سفارش'), ('product', 'محصول'), ('part', 'قطعه'), ('bom', 'BOM'), ('routing', 'مسیر تولید'), ('task', 'تسک تولید'), ('material', 'ماده اولیه'), ('stock_movement', 'حرکت انبار'), ('raw_material', 'ماده خام'), ('supplier', 'تامین\u200cکننده'), ('purchase_order', 'سفارش خرید'), ('worker', 'کارگر'), ('painting_process', 'روند نقاشی'), ('painting_stage', 'مرحله نقاشی')], max_length=30, verbose_name='نوع مهاجرت')),
                ('old_id', models.CharField(max_length=50, verbose_name='شناسه قدیمی')),
                ('new_id', models.CharField(max_length=50, verbose_name='شناسه جدید')),
                ('old_app', models.CharField(blank=True, max_length=50, verbose_name='اپ قدیمی')),
                ('old_model', models.CharField(blank=True, max_length=100, verbose_name='مدل قدیمی')),
                ('new_app', models.CharField(blank=True, max_length=50, verbose_name='اپ جدید')),
                ('new_model', models.CharField(blank=True, max_length=100, verbose_name='مدل جدید')),
                ('is_legacy', models.BooleanField(default=False, verbose_name='قدیمی/میراث')),
                ('legacy_reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل قدیمی بودن')),
                ('migrated_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان مهاجرت')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('migration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='reporting.migrationrun', verbose_name='اجرای مهاجرت')),
            ],
            options={
                'verbose_name': 'نگاشت مهاجرت',
                'verbose_name_plural': 'نگاشت\u200cهای مهاجرت',
                'ordering': ['migration_type', 'old_id'],
                'unique_together': {('migration_type', 'old_id', 'old_app')},
            },
        ),
    ]
