# Generated by Django 5.2.11 on 2026-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='legacy_entity_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='شناسه entity legacy'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='legacy_entity_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع entity legacy'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شناسه هم\u200cبسته'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='legacy_app',
            field=models.CharField(blank=True, max_length=50, verbose_name='اپ legacy'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='شناسه legacy'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='legacy_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدل legacy'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='legacy_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ارجاع legacy'),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='عال'),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=' آخرین اسکن'),
        ),
    ]
