# Generated by Django 5.2.11 on 2026-09-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_barcode_legacy_entity_id_barcode_legacy_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationmap',
            name='migration_type',
            field=models.CharField(choices=[('customer', 'مشتری'), ('order', 'سفارش'), ('order_item', 'آیتم سفارش'), ('product', 'محصول'), ('product_category', 'دسته\u200cبندی محصول'), ('part', 'قطعه'), ('product_part', 'قطعه محصول'), ('production_part', 'قطعه تولید'), ('bom', 'BOM'), ('bom_item', 'آیتم BOM'), ('bom_item_material_rule', 'قانون ماده BOM'), ('routing', 'مسیر تولید'), ('task', 'تسک تولید'), ('material', 'ماده اولیه'), ('raw_material', 'ماده خام'), ('item', 'کالا (Item)'), ('item_category', 'دسته کالا'), ('uom', 'واحد اندازه\u200cگیری'), ('stock_movement', 'حرکت انبار'), ('supplier', 'تامین\u200cکننده'), ('purchase_order', 'سفارش خرید'), ('worker', 'کارگر'), ('worker_profile', 'پروفایل کارگر'), ('painting_process', 'روند نقاشی'), ('painting_stage', 'مرحله نقاشی')], max_length=30, verbose_name='نوع مهاجرت'),
        ),
    ]
