# Generated by Django 5.2.11 on 2026-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_uom_itemcategory_item_stocklocation_stocklot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='consumption_per_unit',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='مصرف هر واحد'),
        ),
    ]
