# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('serial_numbers', models.JSONField(blank=True, default=list, verbose_name='شماره سریال\u200cها')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'آیتم بسته',
                'verbose_name_plural': 'آیتم\u200cهای بسته',
                'ordering': ['package', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackagingSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=50, verbose_name='نوع بسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('items_per_package', models.PositiveIntegerField(verbose_name='تعداد در هر بسته')),
                ('package_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='وزن بسته (کیلوگرم)')),
                ('package_dimensions', models.CharField(blank=True, max_length=100, verbose_name='ابعاد بسته')),
                ('requires_pallet', models.BooleanField(default=False, verbose_name='نیاز به پالت دارد')),
                ('stacking_limit', models.PositiveIntegerField(default=1, verbose_name='حداکثر انباشت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packaging/specs/', verbose_name='تصویر نمونه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مشخصه بسته\u200cبندی',
                'verbose_name_plural': 'مشخصه\u200cهای بسته\u200cبندی',
                'ordering': ['product', 'package_type'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.CharField(max_length=50, verbose_name='شماره بسته')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('packed', 'بسته\u200cبندی شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('returned', 'مرجوع شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('packed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته\u200cبندی')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/packaging/', verbose_name='QR کد')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='وزن (کیلوگرم)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='ابعاد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('customer_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='sales.customerorderitem', verbose_name='آیتم سفارش مشتری')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_packages', to=settings.AUTH_USER_MODEL, verbose_name='بسته\u200cبندی\u200cکننده')),
            ],
            options={
                'verbose_name': 'بسته',
                'verbose_name_plural': 'بسته\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
