# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_uom_itemcategory_item_stocklocation_stocklot_and_more'),
        ('packaging', '0001_initial'),
        ('production', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='production_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorderitem', verbose_name='آیتم سفارش تولید'),
        ),
        migrations.AddField(
            model_name='package',
            name='wip_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.wipunit', verbose_name='واحد WIP'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packaging.package', verbose_name='بسته'),
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_specs', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('customer_order_item', 'package_number')},
        ),
        migrations.AlterUniqueTogether(
            name='packagingspecification',
            unique_together={('product', 'package_type')},
        ),
    ]
