# Generated by Django 5.2.11 on 2026-09-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گروه مشتری',
                'verbose_name_plural': 'گروه\u200cهای مشتری',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی')),
                ('is_representative', models.BooleanField(default=False, verbose_name='نماینده است')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مانده حساب')),
                ('credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سقف اعتبار')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_customers', to=settings.AUTH_USER_MODEL, verbose_name='نماینده')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customergroup', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='نام گیرنده')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='تلفن گیرنده')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'آدرس مشتری',
                'verbose_name_plural': 'آدرس\u200cهای مشتری',
                'ordering': ['-is_default', 'title'],
            },
        ),
    ]
