# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(max_length=50, unique=True, verbose_name='شماره بازرسی')),
                ('inspection_type', models.CharField(choices=[('incoming', 'ورودی'), ('in_process', 'در فرآیند'), ('final', 'نهایی'), ('outgoing', 'خروجی')], max_length=20, verbose_name='نوع بازرسی')),
                ('result', models.CharField(choices=[('pass', 'قبول'), ('fail', 'رد'), ('conditional', 'مشروط'), ('rework', 'بازسازی')], max_length=20, verbose_name='نتیجه')),
                ('inspected_at', models.DateTimeField(verbose_name='زمان بازرسی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بازرس')),
                ('production_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionoperation', verbose_name='عملیات تولید')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='production.productionorder', verbose_name='سفارش تولید')),
            ],
            options={
                'verbose_name': 'بازرسی کیفیت',
                'verbose_name_plural': 'بازرسی\u200cهای کیفیت',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد نقص')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('severity', models.CharField(choices=[('minor', 'جزعی'), ('major', 'عمده'), ('critical', 'بحرانی')], default='minor', max_length=20, verbose_name='شدت')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quality/defects/', verbose_name='تصویر')),
                ('is_reworkable', models.BooleanField(default=True, verbose_name='قابل بازسازی است')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('quality_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='quality.qualityinspection', verbose_name='بازرسی کیفیت')),
            ],
            options={
                'verbose_name': 'نقص کیفیت',
                'verbose_name_plural': 'نقص\u200cهای کیفیت',
                'ordering': ['-severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReworkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rework_number', models.CharField(max_length=50, unique=True, verbose_name='شماره بازسازی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('planned', 'برنامه\u200cریزی شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('defect_description', models.TextField(verbose_name='توضیحات نقص')),
                ('repair_description', models.TextField(verbose_name='روش تعمیر')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('completed_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد تکمیل شده')),
                ('estimated_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه تخمینی')),
                ('actual_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه واقعی')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='شروع برنامه\u200cریزی شده')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='پایان برنامه\u200cریزی شده')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع واقعی')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان واقعی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.worker', verbose_name='مسئول')),
                ('production_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionoperation', verbose_name='عملیات تولید')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_orders', to='production.productionorder', verbose_name='سفارش تولید')),
                ('quality_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_orders', to='quality.qualityinspection', verbose_name='بازرسی کیفیت')),
            ],
            options={
                'verbose_name': 'سفارش بازسازی',
                'verbose_name_plural': 'سفارش\u200cهای بازسازی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReworkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('repair_action', models.CharField(max_length=255, verbose_name='اقدام تعمیر')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('quality_defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.qualitydefect', verbose_name='نقص کیفیت')),
                ('rework_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.reworkorder', verbose_name='سفارش بازسازی')),
            ],
            options={
                'verbose_name': 'آیتم سفارش بازسازی',
                'verbose_name_plural': 'آیتم\u200cهای سفارش بازسازی',
                'ordering': ['rework_order', 'id'],
            },
        ),
    ]
