# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_uom_itemcategory_item_stocklocation_stocklot_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(default='A', max_length=20, verbose_name='Revision')),
                ('effective_date', models.DateField(verbose_name='تاریخ اجرا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'فرمول ساخت (BOM)',
                'verbose_name_plural': 'فرمول\u200cهای ساخت (BOM)',
                'ordering': ['product', '-effective_date'],
                'unique_together': {('product', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد در هر محصول')),
                ('scrap_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ضریب دورریز')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.bom', verbose_name='BOM')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='products.productpart', verbose_name='قطعه')),
            ],
            options={
                'verbose_name': 'آیتم BOM',
                'verbose_name_plural': 'آیتم\u200cهای BOM',
                'ordering': ['bom', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BOMItemMaterialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('standard', 'استاندارد'), ('color_override', 'جایگزینی بر اساس رنگ'), ('size_adjustment', 'تنظیم بر اساس اندازه'), ('alternative', 'جایگزین')], default='standard', max_length=30, verbose_name='نوع قانون')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='شرط')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='مقدار')),
                ('is_primary', models.BooleanField(default=True, verbose_name='اولیه')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('bom_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_rules', to='bom.bomitem', verbose_name='آیتم BOM')),
                ('material_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'قانون ماده BOM',
                'verbose_name_plural': 'قوانین ماده BOM',
                'ordering': ['bom_item', '-is_primary', 'priority'],
            },
        ),
    ]
