# Generated by Django 5.2.11 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('packaging', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=50, unique=True, verbose_name='شماره ارسال')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('ready', 'آماده ارسال'), ('in_transit', 'در حال حمل'), ('delivered', 'تحویل داده شده'), ('returned', 'مرجوع شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='حمل\u200cونقل')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری')),
                ('plate_number', models.CharField(blank=True, max_length=50, verbose_name='شماره پلاک')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='نام راننده')),
                ('driver_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن راننده')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه حمل')),
                ('insurance_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه بیمه')),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='وزن کل (کیلوگرم)')),
                ('total_volume_m3', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='حجم کل (متر مکعب)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای تحویل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='customers.customer', verbose_name='مشتری')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.customerorder', verbose_name='سفارش مشتری')),
            ],
            options={
                'verbose_name': 'ارسال',
                'verbose_name_plural': 'ارسال\u200cها',
                'ordering': ['-shipment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='وزن (کیلوگرم)')),
                ('volume_m3', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='حجم (متر مکعب)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.package', verbose_name='بسته')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipment', verbose_name='ارسال')),
            ],
            options={
                'verbose_name': 'آیتم ارسال',
                'verbose_name_plural': 'آیتم\u200cهای ارسال',
                'ordering': ['shipment', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='وضعیت')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='موقعیت')),
                ('timestamp', models.DateTimeField(verbose_name='زمان')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='shipping.shipment', verbose_name='ارسال')),
            ],
            options={
                'verbose_name': 'پیگیری ارسال',
                'verbose_name_plural': 'پیگیری\u200cهای ارسال',
                'ordering': ['-timestamp'],
            },
        ),
    ]
