# Generated by Django 5.2.11 on 2026-09-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('order_date', models.DateField(verbose_name='تاریخ سفارش')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'بسیار بالا'), (2, 'بالا'), (3, 'متوسط'), (4, 'پایین')], default=3, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('planned', 'برنامه\u200cریزی شده'), ('producing', 'در حال تولید'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ پرداخت\u200cشده')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه حمل')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ نهایی')),
                ('vat_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مالیات ارزش افزوده')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='شرایط پرداخت')),
                ('delivery_terms', models.CharField(blank=True, max_length=100, verbose_name='شرایط تحویل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='مشتری')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_orders', to=settings.AUTH_USER_MODEL, verbose_name='نماینده')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='به\u200cروزرسانی\u200cکننده')),
            ],
            options={
                'verbose_name': 'سفارش مشتری',
                'verbose_name_plural': 'سفارش\u200cهای مشتری',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='اندازه')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد')),
                ('line_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع خط')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='QR کد')),
                ('is_custom', models.BooleanField(default=False, verbose_name='سفارشی')),
                ('production_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای تولید')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='تحویل پیش\u200cبینی شده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.customerorder', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش مشتری',
                'verbose_name_plural': 'آیتم\u200cهای سفارش مشتری',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='شماره پیش\u200cفاکتور')),
                ('quote_date', models.DateField(verbose_name='تاریخ پیش\u200cفاکتور')),
                ('valid_until', models.DateField(verbose_name='معتبر تا')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پیش\u200cفاکتور',
                'verbose_name_plural': 'پیش\u200cفاکتورها',
                'ordering': ['-quote_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف')),
                ('line_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع خط')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='محصول')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesquotation', verbose_name='پیش\u200cفاکتور')),
            ],
            options={
                'verbose_name': 'آیتم پیش\u200cفاکتور',
                'verbose_name_plural': 'آیتم\u200cهای پیش\u200cفاکتور',
                'ordering': ['quotation', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], max_length=20, verbose_name='قطعه')),
                ('code', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('جناغی', 'جناغی'), ('بتنی', 'بتنی')], max_length=20, verbose_name='کد رنگ')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='sales.customerorderitem', verbose_name='آیتم سفارش')),
            ],
            options={
                'verbose_name': 'رنگ آیتم سفارش',
                'verbose_name_plural': 'رنگ\u200cهای آیتم سفارش',
                'unique_together': {('order_item', 'part')},
            },
        ),
    ]
