# Generated by Django 5.2.11 on 2026-09-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصول',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='کد محصول')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='رنگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('default_size', models.CharField(blank=True, max_length=100, verbose_name='سایز پیش\u200cفرض')),
                ('default_colors', models.JSONField(blank=True, default=dict, verbose_name='رنگ\u200cهای پیش\u200cفرض')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت پایه')),
                ('price_increment_per_cm', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد افزایش قیمت به ازای هر سانتی\u200cمتر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('estimated_production_days', models.PositiveIntegerField(default=0, verbose_name='تعداد روز تولید پیش\u200cبینی')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='وزن (کیلوگرم)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='ابعاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قطعه')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='کد قطعه')),
                ('length', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='طول (X)')),
                ('width', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='عرض (Y)')),
                ('thickness', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='ضخامت (Z)')),
                ('grain', models.CharField(choices=[('vertical', 'عمودی'), ('horizontal', 'افقی'), ('none', 'بدون جهت')], default='none', max_length=20, verbose_name='جهت رگه')),
                ('f26', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F26')),
                ('f18', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F18')),
                ('f4', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F4')),
                ('f5', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F5')),
                ('f3', models.CharField(blank=True, max_length=100, verbose_name='بارکد F3')),
                ('f2', models.CharField(blank=True, max_length=100, verbose_name='نام فنی F2')),
                ('pname', models.CharField(blank=True, max_length=100, verbose_name='نام محصول')),
                ('turn', models.BooleanField(default=False, verbose_name='چرخش')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قطعه محصول',
                'verbose_name_plural': 'قطعات محصول',
                'ordering': ['product', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.CharField(max_length=20, verbose_name='شمارهRevision')),
                ('effective_date', models.DateField(verbose_name='تاریخ اجرا')),
                ('description', models.TextField(blank=True, verbose_name='تغییرات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'Revision محصول',
                'verbose_name_plural': 'Revisionهای محصول',
                'ordering': ['-effective_date'],
                'unique_together': {('product', 'revision_number')},
            },
        ),
    ]
